### ISSUE TITLE
ios模拟器报错

### ISSUE THREAD

**Issue by CBCzed** [alibaba/flutter-go#1]
ios模拟器点击组件tab时报错如下：
DB Error: 1 "no such table: cat"
DB Query: SELECT * FROM cat WHERE  depth = 1 and parentId = 0
DB Path: /Users/***/Library/Developer/CoreSimulator/Devices/9F6FDA05-1DF7-4D35-B49A-0FE5E92F9FE8/data/Containers/Data/Application/6D2D5486-A5D6-49BC-9FCE-D80051D9BDA7/Documents/flutter.db
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
DatabaseException(Error Domain=FMDatabase Code=1 "no such table: cat" UserInfo={NSLocalizedDescription=no such table: cat}) sql 'SELECT * FROM cat WHERE  depth = 1 and parentId = 0' args []}
#0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
<asynchronous suspension>
#1      SqfliteDatabase.txnRawQuery.<anonymous closure> (package:sqflite/src/database.dart:330:14)
#2      SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:279:22)
#3      Lock._runTask (package:synchronized/src/synchronized_impl.dart:148:27)
#4      LockBase._createAndRunTask.run (package:synchronized/src/synchronized_impl.dart:62:14)
#5      LockBase._createAndRunTask (package:synchronized/src/synchronized_impl.dart:72:17)
#6      Lock.synchronized (package:synchronized/src/synchronized_impl.dart:140:12)
#7      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:275:37)
<asynchronous suspension>
#8     <…>

**Comment by hanxu317317** [comment]
因为初始化数据库的过程 . 出现了问题. 导致报错. 已经修复了在最新的master代码.

**Comment by hanxu317317** [comment]
请清除本地缓存后. 拉取最新master代码. 我们已经在master中试图解决兼容的问题.

**Comment by erickyim** [comment]
刚才新鲜 clone 的代码，运行之后正常
