### ISSUE TITLE
Vivo Xplay5A卡在首次加载红色界面无法进入主界面

### ISSUE THREAD

**Issue by o0p** [alibaba/flutter-go#125]
![](https://ws1.sinaimg.cn/large/006tNc79ly1g02zwrn99vj30u01hcgnq.jpg)

**Comment by o0p** [comment]
Installing build/app/outputs/apk/app.apk...                        13.4s
E/flutter (22997): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'window' was called on null.
E/flutter (22997): Receiver: null
E/flutter (22997): Tried calling: window
E/flutter (22997): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
E/flutter (22997): #1      BinaryMessages._sendPlatformMessage (package:flutter/src/services/platform_messages.dart:40:30)
E/flutter (22997): #2      BinaryMessages.send (package:flutter/src/services/platform_messages.dart:88:12)
E/flutter (22997): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:295:50)
E/flutter (22997): <asynchronous suspension>
E/flutter (22997): #4      invokeMethod (package:sqflite/src/sqflite_impl.dart:25:28)
E/flutter (22997): <asynchronous suspension>
E/flutter (22997): #5      SqfliteDatabaseFactory.invokeMethod (package:sqflite/src/database_factory.dart:91:7)
E/flutter (22997): #6      SqfliteDatabaseFactory.getDatabasesPath.<anonymous closure> (package:sqflite/src/database_factory.dart:182:16)
E/flutter (22997): #7      wrapDatabaseException (package:sqflite/src/exception.dart:121:28)
E/flutter (22997): <asynchronous suspension>
E/flutter (22997): #8      SqfliteDatabaseFactory.getDatabasesPath (package:sqflite/src/database_factory.dart:181:24)
E/flutter (22997): <asynchronous suspension>
E/flutter (22997): #9      getDatabasesPath (package:sqflite/sqflite.dart:353:54)
E/flutter (22997): #10     Provider.init (package:flutter_go/utils/provider.dart:60:34)
E/flutter (22997): <asynchronous suspension>
E/flutter (22997): #11     main (package:flutter_go/main.dart:58:18)
E/flutter (22997): <asynchronous suspension>
E/flutter (22997): #12     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:170:23)
E/flutter (22997): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (22997): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (22997): #15     _runZoned (dart:async/zone.dart:1516:10)
E/flutter (22997): #16     runZoned (dart:async/zone.dart:1500:12)
E/flutter (22997): #17     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:169:5)
E/flutter (22997): #18     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:300:19)
E/flutter (22997): #19     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
E/flutter (22997): 
V/ResourcesManager(22997): Skipping new config: curSeq=7, newSeq=7
I/Timeline(22997): Timeline: Activity_idle id: android.os.BinderProxy@18d3d673 time:1316157
 8,015ms (!)                                                                                                                                                    🔥  To hot reload changes while running, press "r". To hot restart (and rebuild state), press "R".                                                              An Observatory debugger and profiler on vivo Xplay5A is available at:
http://127.0.0.1:62233/
For a more detailed help message, press "h". To detach, press "d"; to quit,
press "q".

                                                                                                                                                                                                                                                                                                                           ⡿ (This is taking an unexpectedly long time.)Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
Error -32601 received from application: Method not found
                                                                                Reloaded 0 of 914 libraries in 3,931ms.

**Comment by o0p** [comment]
flutter自己的bug，升级flutter以后解决。

**Comment by hanjianfei** [comment]
我现在版本是1.0.0 升级到哪个版本？

**Comment by hanxu317317** [comment]
@hanjianfei 我们会盘查一下问题. 你可以手动修改xcode的配置. 把欢迎界面去掉.
