### ISSUE TITLE
WIDGET中的组件无法点击

### ISSUE THREAD

**Issue by asphg** [alibaba/flutter-go#163]
为什么WIDGET和动态中的列表和控件无法点击

**Comment by hanxu317317** [comment]
这个问题. 还真的没有人反馈过来. 有什么报错信息么?

**Comment by stack-stark** [comment]
WIDGET在真机上运行是空白

**Comment by goodcs1928** [comment]
为什么WIDGET和动态中的列表和控件无法点击   --> 我也是遇到了这个问题,  层级多了就容易出现, 不知什么原因
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
                                                                                   Receiver: null
                                                                                   Tried calling: iterator
                                                                                   #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
                                                                                   #1      SweepCodeManager.sweepCodeInfo (package:intelligent_electronic_scale/dao/SweepCodeManager.dart:64:26)
                                                                                   <asynchronous suspension>
                                                                                   #2      _ScannerResultPage._scannerCodeInfo (package:intelligent_electronic_scale/page/ScannerResultPage.dart:75:72)
                                                                                   <asynchronous suspension>
                                                                                   #3      _ScannerResultPage.initState (package:intelligent_electronic_scale/page/ScannerResultPage.dart:91:5)
                                                                                   #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
                                                                                   #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
                                                                                   #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
                                                                                   #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
                                                                                   #8      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
                                                                                   #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
                                                                                   #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
                                                                                   #11     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
                                                                                   #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
                                                                                   #13     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
                                                                                   #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
                                                                                   #15     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
                                                                                   #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
                                                                                   #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
                                                                                   #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
                                                                                   #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
                                                                                   #20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
                                                                                   #21     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
                                                                                   #22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
                                                                                   #23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
                                                                                   #24     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
                                                                                   #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
                                                                                   #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
                                                                                   #27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
                                                                                   #28     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
                                                                                   #29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
                                                                                   #30     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
                                                                                   #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
                                                                                   #32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
                                                                                   #33     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
                                                                                   #34     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
                                                                                   #35     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1015:20)
                                                                                   #36     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2253:19)
                                                                                   #37     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1008:11)
                                                                                   #38     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:274:23)
                                                                                   #39     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1728:58)
                                                                                   #40     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:797:15)
                                                                                   #41     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1728:13)
                                                                                   #42     RenderSliverMu
