### ISSUE TITLE
【小米8】首次运行，widget页面白屏，无法加载控件示例

### ISSUE THREAD

**Issue by doomsdayer** [alibaba/flutter-go#171]
异常信息如下

E/flutter ( 5668): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: DatabaseException(database_closed 1)
E/flutter ( 5668): #0      wrapDatabaseException (package:sqflite/src/exception.dart:125:7)
E/flutter ( 5668): <asynchronous suspension>
E/flutter ( 5668): #1      SqfliteDatabase.txnRawQuery.<anonymous closure> (package:sqflite/src/database.dart:330:14)
E/flutter ( 5668): #2      SqfliteDatabase.txnSynchronized.<anonymous closure> (package:sqflite/src/database.dart:279:22)
E/flutter ( 5668): #3      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:31:26)
E/flutter ( 5668): <asynchronous suspension>
E/flutter ( 5668): #4      SqfliteDatabase.txnSynchronized (package:sqflite/src/database.dart:275:37)
E/flutter ( 5668): <asynchronous suspension>
E/flutter ( 5668): #5      SqfliteDatabase.txnRawQuery (package:sqflite/src/database.dart:329:12)
E/flutter ( 5668): #6      SqfliteDatabaseExecutor.rawQuery (package:sqflite/src/database.dart:92:10)
E/flutter ( 5668): #7      SqfliteDatabaseExecutor.query (package:sqflite/src/database.dart:86:12)
E/flutter ( 5668): #8      Sql.getByCondition (package:flutter_go/utils/sql.dart:58:23)
E/flutter ( 5668): <asynchronous suspension>
E/flutter ( 5668): #9      CatControlModel.getList (package:flutter_go/model/cat.dart:91:32)
E/flutter ( 5668): <asynchronous suspension>
E/flutter ( 5668): #10     SecondPageState.renderCats (package:flutter_go/views/widget_page/widget_page.dart:42:14)
E/flutter ( 5668): #11     SecondPageState.initState (package:flutter_go/views/widget_page/widget_page.dart:38:5)
E/flutter ( 5668): #12     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3846:58)
E/flutter ( 5668): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 5668): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 5668): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 5668): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 5668): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 5668): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 5668): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4876:14)
E/flutter ( 5668): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 5668): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 5668): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 5668): #23     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 5668): #24     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter ( 5668): #25     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 5668): #26     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 5668): #27     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 5668): #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 5668): #29     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 5668): #30     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter ( 5668): #31     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 5668): #32     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4063:11)
E/flutter ( 5668): #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 5668): #34     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 5668): #35     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3747:16)
E/flutter ( 5668): #36     Element.rebuild (package:flutter/src/widgets/framework.dart:3559:5)
E/flutter ( 5668): #37     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3716:5)
E/flutter ( 5668): #38     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3864:11)
E/flutter ( 5668): #39     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3711:5)
E/flutter ( 5668): #40     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2956:14)
E/flutter ( 5668): #41     Element.updateChild (package:flutter/src/widgets/framework.dart:2759:12)
E/flutter ( 5668): #42     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1030:36)
E/flutter ( 5668): #43     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1015:20)
E/flutter ( 5668): #44     BuildOwner.buildScope (package:flut

**Comment by hanxu317317** [comment]
sqlite一直有问题. 我们现在在处理. 数据网络化.  下一期我们会统一处理这个问题

**Comment by forvenus** [comment]
小米8同样问题
