### ISSUE TITLE
编译错误: Finished with error: ProcessException: Process "E:\flutter\flutter-go\android\gradlew.bat" exited abnormally:

### ISSUE THREAD

**Issue by jp1017** [alibaba/flutter-go#175]
>Launching lib\main.dart on OD105 in debug mode...
Initializing gradle...
Finished with error: ProcessException: Process "E:\flutter\flutter-go\android\gradlew.bat" exited abnormally:
Exception in thread "main" java.lang.NullPointerException
	at org.gradle.wrapper.BootstrapMainStarter.findLauncherJar(BootstrapMainStarter.java:34)
	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:25)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
  Command: E:\flutter\flutter-go\android\gradlew.bat -v

**Comment by jp1017** [comment]
gradle 的鬼，修改 `android/gradle/wrapper/gradle-wrapper.properties` 版本为4.10.3，（4.6没安装）
