### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by liminwanqing** [alibaba/flutter-go#412]
Compiler message:                                                       
../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed                                     
Try to either                                                           
 - provide an implementation,                                           
 - inherit an implementation from a superclass or mixin,                
 - mark the class as abstract, or                                       
 - provide a 'noSuchMethod' implementation.                             
                                                                        
class InputConnectionController implements TextInputClient {            
      ^^^^^^^^^^^^^^^^^^^^^^^^^                                         
../flutter/packages/flutter/lib/src/services/text_input.dart:658:8: Context: 'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();                                              
       ^^^^^^^^^^^^^^^^                                                 
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
#0      KernelSnapshot.build (package:flutter_tools/src/build_system/targets/dart.dart:213:7)
<asynchronous suspension>                                               
#1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:526:25)
<asynchronous suspension>                                               
#2      _BuildInstance.invokeTarget.<anonymous closure> (package:flutter_tools/src/build_system/build_system.dart:481:35)
#3      new Future.sync (dart:async/future.dart:222:31)                 
#4      AsyncMemoizer.runOnce (package:async/src/async_memoizer.dart:43:45)
#5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:481:21)
<asynchronous suspension>                                               
<asynchronous suspension>                                               
#6      BuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:419:36)
<asynchronous suspension>                                               
#7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:154:50)
<asynchronous suspension>                                               
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:556:18)
<asynchronous suspension>                                               
#9      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:456:33)
<asynchronous suspension>                                               
#10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>                                               
#11     _rootRun (dart:async/zone.dart:1124:13)                         
#12     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#13     _runZoned (dart:async/zone.dart:1516:10)                        
#14     runZoned (dart:async/zone.dart:1463:12)                         
#15     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>                                               
#16     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:446:20)
#17     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>                                               
#18     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:416:21)
<asynchronous suspension>                                               
#19     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>                                               
#20     _rootRun (dart:async/zone.dart:1124:13)                         
#21     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#22     _runZoned (dart:async/zone.dart:1516:10)                        
#23     runZoned (dart:async/zone.dart:1463:12)                         
#24     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>                                               
#25     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:367:19)
<asynchronous suspension>                                               
#26     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#27     new Future.sync (dart:async/future.dart:222:31)                 
#28     CommandRunner.run (package:args/command_runner.dart:112:14)     
#29     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:251:18)
#30     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:63:22)
<asynchronous suspension>                                               
#31     _rootRun (dart:async/zone.dart:1124:13)                         
#32     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#33     _runZoned (dart:async/zone.dart:1516:10)                        
#34     runZoned (dart:async/zone.dart:1500:12)                         
#35     run.<anonymous closure> (package:flutter_tools/runner.dart:61:18)
<asynchronous suspension>                                               
#36     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:146:29)
<asynchronous suspension>                                               
#37     _rootRun (dart:async/zone.dart:1124:13)                         
#38     _CustomZone.run (dart:async/zone.dart:1021:19)                  
#39     _runZoned (dart:async/zone.dart:1516:10)                        
#40     runZoned (dart:async/zone.dart:1463:12)                         
#41     AppContext.run (package:flutter_tools/src/base/context.dart:145:18)
<asynchronous suspension>                                               
#42     runInContext (package:flutter_tools/src/context_runner.dart:65:24)
<asynchronous suspension>                                               
#43     run (package:flutter_tools/runner.dart:50:10)                   
#44     main (package:flutter_tools/executable.dart:65:9)               
<asynchronous suspension>                                               
#45     main (file:///Users/limin/work/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#46     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#47     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
                                                                        
build failed.                                                           
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/Users/limin/work/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 716
                                                                        
* What went wrong:                                                      
Execution failed for task ':app:compileFlutterBuildDebugArm64'.         
> Process 'command '/Users/limin/work/flutter/bin/flutter'' finished with non-zero exit value 1
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 1m 32s                                                  
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        92.8s
Gradle task assembleDebug failed with exit code 1

**Comment by 596932151** [comment]
我也碰到这个问题，请问解决了吗

**Comment by 465789287** [comment]
我也卡在这个问题，请问如何解决？

**Comment by CoderSamz** [comment]
> Compiler message:
../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error:

这问题应该是zefyr的master没更新导致的，zefyr的master没跟上Flutter的速度😂

解决方案一：
修改包依赖的分支(zefyr有这个修复分支，只是还没合并)
```yaml
  zefyr:
      git:
        url: git://github.com/memspace/zefyr.git
        ref: fix-text-input-connection-closed
        path: packages/zefyr
```

解决方案二：
自己改源码
`../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart`这是楼主的路径，以这个路径为例，找到自己对应的zefyr的源文件进行修改

添加以下实现代码
```dart
  @override
  void connectionClosed() {
    if (hasConnection) {
      _textInputConnection.connectionClosedReceived();
      _textInputConnection = null;
      _lastKnownRemoteTextEditingValue = null;
      _sentRemoteValues.clear();
    }
  }
```


解决方案信息源自
[zefyr issues #210](https://github.com/memspace/zefyr/issues/210)
[zefyr issues #205 ](https://github.com/memspace/zefyr/issues/205)

**Comment by orliXdx** [comment]
赞一个 解决了

**Comment by pulyaevskiy** [comment]
Fixed in zefyr 0.9. Closing this is resolved

**Comment by lilixiang5473** [comment]
我照着你提供的方法改了 一样的问题 并没有解决是为什么呢？

**Comment by lilixiang5473** [comment]
> > Compiler message:
> > ../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error:
> 
> 这问题应该是zefyr的master没更新导致的，zefyr的master没跟上Flutter的速度😂
> 
> 我当前的Flutter版本
> 
> ```
> Flutter 1.12.13+hotfix.5 • channel stable •
> Dart 2.7.0
> ```
> 
> 解决方案一：
> 
> 修改包依赖的分支(zefyr有这个修复分支，只是还没合并)
> 
> 修改项目文件flutter-go/pubspec.yaml
> 
> ```yaml
> # zefyr: ^0.8.0
>   zefyr:
>       git:
>         url: git://github.com/memspace/zefyr.git
>         ref: fix-text-input-connection-closed
>         path: packages/zefyr
> ```
> 
> 解决方案二：
> 自己改源码
> `../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart`这是楼主的路径，以这个路径为例，找到自己对应的zefyr的源文件进行修改
> 
> 添加以下实现代码
> 
> ```dart
>   @override
>   void connectionClosed() {
>     if (hasConnection) {
>       _textInputConnection.connectionClosedReceived();
>       _textInputConnection = null;
>       _lastKnownRemoteTextEditingValue = null;
>       _sentRemoteValues.clear();
>     }
>   }
> ```
> 
> 解决方案三：
> 
> zefyr 在0.9.0已经修复好了，所以更换zefyr版本再更新pub就行了
> 
> 修改项目文件flutter-go/pubspec.yaml
> 
> ```yaml
>  zefyr: ^0.9.0
> ```
> 
> 解决方案信息源自
> [zefyr issues #210](https://github.com/memspace/zefyr/issues/210)
> [zefyr issues #205 ](https://github.com/memspace/zefyr/issues/205)



> > Compiler message:
> > ../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error:
> 
> 这问题应该是zefyr的master没更新导致的，zefyr的master没跟上Flutter的速度😂
> 
> 我当前的Flutter版本
> 
> ```
> Flutter 1.12.13+hotfix.5 • channel stable •
> Dart 2.7.0
> ```
> 
> 解决方案一：
> 
> 修改包依赖的分支(zefyr有这个修复分支，只是还没合并)
> 
> 修改项目文件flutter-go/pubspec.yaml
> 
> ```yaml
> # zefyr: ^0.8.0
>   zefyr:
>       git:
>         url: git://github.com/memspace/zefyr.git
>         ref: fix-text-input-connection-closed
>         path: packages/zefyr
> ```
> 
> 解决方案二：
> 自己改源码
> `../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart`这是楼主的路径，以这个路径为例，找到自己对应的zefyr的源文件进行修改
> 
> 添加以下实现代码
> 
> ```dart
>   @override
>   void connectionClosed() {
>     if (hasConnection) {
>       _textInputConnection.connectionClosedReceived();
>       _textInputConnection = null;
>       _lastKnownRemoteTextEditingValue = null;
>       _sentRemoteValues.clear();
>     }
>   }
> ```
> 
> 解决方案三：
> 
> zefyr 在0.9.0已经修复好了，所以更换zefyr版本再更新pub就行了
> 
> 修改项目文件flutter-go/pubspec.yaml
> 
> ```yaml
>  zefyr: ^0.9.0
> ```
> 
> 解决方案信息源自
> [zefyr issues #210](https://github.com/memspace/zefyr/issues/210)
> [zefyr issues #205 ](https://github.com/memspace/zefyr/issues/205)

我照着你提供的方法改了 一样的问题 并没有解决是为什么呢？

**Comment by CoderSamz** [comment]
> > > Compiler message:
> > > ../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error:
> > 
> > 
> > 这问题应该是zefyr的master没更新导致的，zefyr的master没跟上Flutter的速度😂
> > 我当前的Flutter版本
> > ```
> > Flutter 1.12.13+hotfix.5 • channel stable •
> > Dart 2.7.0
> > ```
> > 
> > 
> > 解决方案一：
> > 修改包依赖的分支(zefyr有这个修复分支，只是还没合并)
> > 修改项目文件flutter-go/pubspec.yaml
> > ```yaml
> > # zefyr: ^0.8.0
> >   zefyr:
> >       git:
> >         url: git://github.com/memspace/zefyr.git
> >         ref: fix-text-input-connection-closed
> >         path: packages/zefyr
> > ```
> > 
> > 
> > 解决方案二：
> > 自己改源码
> > `../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart`这是楼主的路径，以这个路径为例，找到自己对应的zefyr的源文件进行修改
> > 添加以下实现代码
> > ```dart
> >   @override
> >   void connectionClosed() {
> >     if (hasConnection) {
> >       _textInputConnection.connectionClosedReceived();
> >       _textInputConnection = null;
> >       _lastKnownRemoteTextEditingValue = null;
> >       _sentRemoteValues.clear();
> >     }
> >   }
> > ```
> > 
> > 
> > 解决方案三：
> > zefyr 在0.9.0已经修复好了，所以更换zefyr版本再更新pub就行了
> > 修改项目文件flutter-go/pubspec.yaml
> > ```yaml
> >  zefyr: ^0.9.0
> > ```
> > 
> > 
> > 解决方案信息源自
> > [zefyr issues #210](https://github.com/memspace/zefyr/issues/210)
> > [zefyr issues #205 ](https://github.com/memspace/zefyr/issues/205)
> 
> > > Compiler message:
> > > ../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error:
> > 
> > 
> > 这问题应该是zefyr的master没更新导致的，zefyr的master没跟上Flutter的速度😂
> > 我当前的Flutter版本
> > ```
> > Flutter 1.12.13+hotfix.5 • channel stable •
> > Dart 2.7.0
> > ```
> > 
> > 
> > 解决方案一：
> > 修改包依赖的分支(zefyr有这个修复分支，只是还没合并)
> > 修改项目文件flutter-go/pubspec.yaml
> > ```yaml
> > # zefyr: ^0.8.0
> >   zefyr:
> >       git:
> >         url: git://github.com/memspace/zefyr.git
> >         ref: fix-text-input-connection-closed
> >         path: packages/zefyr
> > ```
> > 
> > 
> > 解决方案二：
> > 自己改源码
> > `../../.pub-cache/hosted/pub.dartlang.org/zefyr-0.8.0/lib/src/widgets/input.dart`这是楼主的路径，以这个路径为例，找到自己对应的zefyr的源文件进行修改
> > 添加以下实现代码
> > ```dart
> >   @override
> >   void connectionClosed() {
> >     if (hasConnection) {
> >       _textInputConnection.connectionClosedReceived();
> >       _textInputConnection = null;
> >       _lastKnownRemoteTextEditingValue = null;
> >       _sentRemoteValues.clear();
> >     }
> >   }
> > ```
> > 
> > 
> > 解决方案三：
> > zefyr 在0.9.0已经修复好了，所以更换zefyr版本再更新pub就行了
> > 修改项目文件flutter-go/pubspec.yaml
> > ```yaml
> >  zefyr: ^0.9.0
> > ```
> > 
> > 
> > 解决方案信息源自
> > [zefyr issues #210](https://github.com/memspace/zefyr/issues/210)
> > [zefyr issues #205 ](https://github.com/memspace/zefyr/issues/205)
> 
> 我照着你提供的方法改了 一样的问题 并没有解决是为什么呢？

你采用哪个方案，新版的`zefyr`已经没这个问题了，直接用方案三就行了
