### ISSUE TITLE
Launching lib/main.dart on MP1718 in debug mode... Initializing gradle...                                                 ⣯ Oops; flutter has exited unexpectedly.                 Crash report written to /Users/meetyou/MyProject/flutter-go/flutter_01.log; please let us know at https://github.com/flutter/flutter/issues.        ⣽%                                            

### ISSUE THREAD

**Issue by xiaoyaomeng** [alibaba/flutter-go#433]
Launching lib/main.dart on MP1718 in debug mode...
Initializing gradle...                                                 ⣯
Oops; flutter has exited unexpectedly.
        
       Crash report written to /Users/meetyou/MyProject/flutter-go/flutter_01.log;
please let us know at https://github.com/flutter/flutter/issues.
       ⣽%

**Comment by xiaoyaomeng** [comment]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "/Users/meetyou/MyProject/flutter-go/android/gradlew" exited abnormally:
Downloading https://services.gradle.org/distributions/gradle-4.10.2-all.zip


Exception in thread "main" javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
	at org.gradle.wrapper.Download.download(Download.java:44)
	at org.gradle.wrapper.Install$1.call(Install.java:61)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
	... 16 more
  Command: /Users/meetyou/MyProject/flutter-go/android/gradlew -v

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      _initializeGradle (package:flutter_tools/src/android/gradle.dart:225:9)
<asynchronous suspension>
#2      _ensureGradle (package:flutter_tools/src/android/gradle.dart:206:37)
<asynchronous suspension>
#3      _readGradleProject (package:flutter_tools/src/android/gradle.dart:134:31)
<asynchronous suspension>
#4      _gradleProject (package:flutter_tools/src/android/gradle.dart:111:34)
<asynchronous suspension>
#5      getGradleAppOut (package:flutter_tools/src/android/gradle.dart:105:29)
<asynchronous suspension>
#6      AndroidApk.fromAndroidProject (package:flutter_tools/src/application_package.dart:160:23)
<asynchronous suspension>
#7      ApplicationPackageFactory.getPackageForPlatform (package:flutter_tools/src/application_package.dart:47:32)
<asynchronous suspension>
#8      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:352:56)
<asynchronous suspension>
#9      HotRunner.run (package:flutter_tools/src/run_hot.dart:247:39)
<asynchronous suspension>
#10     RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:476:37)
<asynchronous suspension>
#11     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:477:18)
<asynchronous suspension>
#12     FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:383:33)
<asynchronous suspension>
#13     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#14     _rootRun (dart:async/zone.dart:1124:13)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _runZoned (dart:async/zone.dart:1516:10)
#17     runZoned (dart:async/zone.dart:1463:12)
#18     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:375:20)
#20     CommandRunner.runCommand (package:args/command_runner.dart:197:27)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:396:21)
<asynchronous suspension>
#22     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#23     _rootRun (dart:async/zone.dart:1124:13)
#24     _CustomZone.run (dart:async/zone.dart:1021:19)
#25     _runZoned (dart:async/zone.dart:1516:10)
#26     runZoned (dart:async/zone.dart:1463:12)
#27     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#28     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:356:19)
<asynchronous suspension>
#29     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:112:25)
#30     new Future.sync (dart:async/future.dart:224:31)
#31     CommandRunner.run (package:args/command_runner.dart:112:14)
#32     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:242:18)
#33     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:22)
<asynchronous suspension>
#34     _rootRun (dart:async/zone.dart:1124:13)
#35     _CustomZone.run (dart:async/zone.dart:1021:19)
#36     _runZoned (dart:async/zone.dart:1516:10)
#37     runZoned (dart:async/zone.dart:1500:12)
#38     run.<anonymous closure> (package:flutter_tools/runner.dart:60:18)
<asynchronous suspension>
#39     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:154:29)
<asynchronous suspension>
#40     _rootRun (dart:async/zone.dart:1124:13)
#41     _CustomZone.run (dart:async/zone.dart:1021:19)
#42     _runZoned (dart:async/zone.dart:1516:10)
#43     runZoned (dart:async/zone.dart:1463:12)
#44     AppContext.run (package:flutter_tools/src/base/context.dart:153:18)
<asynchronous suspension>
#45     runInContext (package:flutter_tools/src/context_runner.dart:56:24)
<asynchronous suspension>
#46     run (package:flutter_tools/runner.dart:51:10)
#47     main (package:flutter_tools/executable.dart:62:9)
<asynchronous suspension>
#48     main (file:///Users/meetyou/flutter_sdk/packages/flutter_tools/bin/flutter_tools.dart:8:3)
#49     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#50     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel unknown, v1.8.2, on Mac OS X 10.13.6 17G65, locale zh-Hans-CN)
    [32m•[39m Flutter version 1.8.2 at /Users/meetyou/flutter_sdk
    [32m•[39m Framework revision 0a39d8d92e (6 months ago), 2019-07-10 19:17:14 -0700
    [32m•[39m Engine revision 75387dbc14
    [32m•[39m Dart version 2.5.0 (build 2.5.0-dev.0.0 b5aeaa6796)

[33m[!][39m Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    [32m•[39m Android SDK at /Users/meetyou/Library/Android/sdk
    [32m•[39m Android NDK at /Users/meetyou/Library/Android/sdk/ndk-bundle
    [32m•[39m Platform android-29, build-tools 29.0.2
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    [33m![39m Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[33m[!][39m Xcode - develop for iOS and macOS
    [31m✗[39m Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    [31m✗[39m CocoaPods installed but not initialized.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart
        side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To initialize CocoaPods, run:
        pod setup
      once to finalize CocoaPods' installation.

[32m[✓][39m iOS tools - develop for iOS devices
    [32m•[39m ios-deploy 1.9.4

[32m[✓][39m Chrome - develop for the web
    [32m•[39m Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[32m[✓][39m Android Studio (version 3.2)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 31.3.1
    [32m•[39m Dart plugin version 181.5656
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[33m[!][39m IntelliJ IDEA Community Edition (version 2018.3.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA CE.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.1.3)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m Connected device (3 available)
    [32m•[39m MP1718 • e1fec4b2 • android-arm64  • Android 8.1.0 (API 27)
    [32m•[39m macOS  • macOS    • darwin-x64     • Mac OS X 10.13.6 17G65
    [32m•[39m Chrome • chrome   • web-javascript • Google Chrome 79.0.3945.88 


[33m![39m Doctor found issues in 4 categories.
```
