### ISSUE TITLE
flutter run 执行报错

### ISSUE THREAD

**Issue by dabaoRain** [alibaba/flutter-go#526]
flutter packages get 执行后 页面很多文件都显示红色报错

flutter run 执行报下面的错误

`Compiler message:
../../tools/flutter_windows_1.17.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members: - TextInputClient.connectionClosed
 - TextInputClient.currentTextEditingValue
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {    
      ^^^^^^^^^^^^^^^^^^^^^^^^^
../../tools/flutter_windows_1.17.0-stable/flutter/packages/flutter/lib/src/services/text_input.dart:762:8: Context:  
'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();
       ^^^^^^^^^^^^^^^^
../../tools/flutter_windows_1.17.0-stable/flutter/packages/flutter/lib/src/services/text_input.dart:757:24: Context:
'TextInputClient.currentTextEditingValue' is defined here.
  TextEditingValue get currentTextEditingValue;
                       ^^^^^^^^^^^^^^^^^^^^^^^
../../tools/flutter_windows_1.17.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.2.2/lib/src/dio_http_headers.dart:55:8: Error: The method 'DioHttpHeaders.add' has fewer named arguments than those of overridden method      
'HttpHeaders.add'.
  void add(String name, value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:694:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
../../tools/flutter_windows_1.17.0-stable/flutter/.pub-cache/hosted/pub.flutter-io.cn/dio-2.2.2/lib/src/dio_http_headers.dart:70:8: Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method      
'HttpHeaders.set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///third_party/dart/sdk/lib/_http/http.dart:703:8: Context: This is the overridden method ('set').  
  void set(String name, Object value,
       ^
lib/views/welcome_page/fourth_page.dart:95:13: Error: 'Page' is imported from both
'package:flutter/src/widgets/navigator.dart' and 'package:flutter_go/views/fourth_page/pages.dart'.
        new Page(
            ^^^^
lib/views/welcome_page/fourth_page.dart:102:22: Error: 'Page' is imported from both
'package:flutter/src/widgets/navigator.dart' and 'package:flutter_go/views/fourth_page/pages.dart'.
          child: new Page(
                     ^^^^
lib/components/search_input.dart:300:11: Error: No named parameter with the name 'isInitialRoute'.
          isInitialRoute: false,
          ^^^^^^^^^^^^^^
../../tools/flutter_windows_1.17.0-stable/flutter/packages/flutter/lib/src/widgets/navigator.dart:458:9: Context:
Found this candidate, but the arguments don't match.
  const RouteSettings({
        ^^^^^^^^^^^^^
Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)   
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:666)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)      
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)  
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:58)
        at org.gradle.wrapper.Download.download(Download.java:44)
        at org.gradle.wrapper.Install$1.call(Install.java:61)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)`

**Comment by yeguoqiang** [comment]
我也是报这个错，咋解决

**Comment by yeguoqiang** [comment]
flutter doctor 运行结果：
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.2, on Microsoft Windows [Version 10.0.18363.836], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

需要做以下事情才能run起来
1.dio依赖更新到最新版本 dio: ^3.0.9，解决Error: The method 'DioHttpHeaders.set' has fewer named arguments than those of overridden method
2.zefyr更新到最新版本 zefyr: ^0.11.0，解决'TextInputClient.currentTextEditingValue' is defined here
3.注释isInitialRoute用到的地方，Error: No named parameter with the name 'isInitialRoute'
4.Error: 'Page' is imported from both，Page包与Flutter官方的冲突，把Flutter-Go的Page.dart文件改名，比如FPage.dart
5.报ZefyrThemeData参数的问题，直接改成ZefyrThemeData()，不传参数
6.报找不到CookieManager类，注释掉使用到CookieManager的地方即可
7.最后run的时候如果报下不了arm相关的jar包，需要科学上网了。。
解决以上问题，基本就可以run了
