### ISSUE TITLE
ios使用CocoaPods 安装执行 pod install 报错

### ISSUE THREAD

**Issue by DolphinsLoveCats** [alibaba/flutter-go#89]
cocopods版本:1.5.3
信息
pod install
Generated.xcconfig must exist. If you're running pod install manually, make sure flutter packages get is executed first.
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 0 dependencies from the Podfile and 0 total pods installed.

如何解决?

**Comment by hanxu317317** [comment]
make sure flutter packages get is executed first ?

**Comment by ckjbug** [comment]
期待能release一个iOS版本

**Comment by hanxu317317** [comment]
@ckjbug 我们正在筹备ios的事情. 不久就会发布ios版

**Comment by ruanchaohouzi** [comment]
Android运行正常，ios运行报错，现在还不支持ios设备吗？
报错信息：
Error running pod install
Error launching application on iPhone XS Max.

**Comment by ruanchaohouzi** [comment]
Android运行正常，ios运行报错，现在还不支持ios设备吗？
报错信息：
Error output from CocoaPods:
↳
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/executable.rb:89: warning: Insecure world writable dir /usr/local/share/dotnet in PATH, mode 040777
    /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:83:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
    Did you mean?  tap
    	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:32:in `search'
    	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:65:in `search_query'
    	from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:59:in `search_exception'
    	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
    	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:67:in `report_error'
    	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
    	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run'
    	from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
    	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
    	from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
    	from /usr/local/bin/pod:22:in `load'
    	from /usr/local/bin/pod:22:in `<main>'
Error running pod install
Error launching application on iPhone XS Max.

**Comment by findonecity** [comment]
android 运行ok，ios运行报 
Launching lib/main.dart on iPhone XR in debug mode...
Warning: CocoaPods installed but not initialized. Skipping pod install.
  CocoaPods is used to retrieve the iOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without resolving iOS dependencies with CocoaPods, plugins will not work on iOS.
  For more info, see https://flutter.io/platform-plugins
To initialize CocoaPods, run:
  pod setup
once to finalize CocoaPods' installation.
Running Xcode build...
Xcode build done.                                            1.3s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    Debug.xcconfig line 1: Unable to find included file "Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig"
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

Could not build the application for the simulator.
Error launching application on iPhone XR.

我是一个初学者，想运行项目到ios手看看效果

**Comment by DeckeDeng** [comment]
控制平台敲命令行：flutter doctor 
然后根据提示安装配置…iOS就应该不会有问题了…

**Comment by DogTwoChen** [comment]
> Android运行正常，ios运行报错，现在还不支持ios设备吗？
> 报错信息：
> Error output from CocoaPods:
> ↳
> /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/executable.rb:89: warning: Insecure world writable dir /usr/local/share/dotnet in PATH, mode 040777
> /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:83:in `parse_results': undefined method `map' for nil:NilClass (NoMethodError)
> Did you mean? tap
> from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/sidekick.rb:32:in `search' from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:65:in `search_query'
> from /Library/Ruby/Gems/2.3.0/gems/gh_inspector-1.0.3/lib/gh_inspector/inspector.rb:59:in `search_exception' from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/user_interface/error_report.rb:119:in `search_for_exceptions'
> from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:67:in `report_error' from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:396:in `handle_exception'
> from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:337:in `rescue in run' from /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:324:in `run'
> from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run' from /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
> from /usr/local/bin/pod:22:in `load' from /usr/local/bin/pod:22:in `
> 
> '
> Error running pod install
> Error launching application on iPhone XS Max.


升级一下你的ruby  https://gems.ruby-china.org这个已经不能用了

**Comment by practiceqian** [comment]
clone到本地需要用编译器先打开运行在模拟器上一下，我直接用xcode打开wordspace报错了，打开vscode用模拟器运行一遍再重新开workspace就可以正常安装了

**Comment by zhuozhao** [comment]
Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error: CocoaPods's specs repository is too out-of-date to satisfy dependencies.
To update the CocoaPods specs, run:
  pod repo update

Error running pod install
Error launching application on iPhone Xʀ.

我的其他项目 都没有问题，这个项目clone下来 就是跑步起来，重新clone 编译 还是不行啊，有没有一样的问题；谁能help me

**Comment by julytian** [comment]
@zhuozhao ,试下cocoapods更新到最新的版本：
```
sudo gem install cocoapods --pre
```
然后将根目录下pubspec.yaml文件中 firebase_analytics: ^2.0.2+1 改为 firebase_analytics: ^3.0.1 之后运行 `flutter clean`  然后执行 `flutter run` 试下

**Comment by aboutmydreams** [comment]
some problem
